name = "backend"
main = "worker.js"
compatibility_date = "2026-03-28"

[[d1_databases]]
binding = "DB" 
database_name = "fixlog" 
database_id = "e765c5e3-c2d5-4744-b2dd-bf18f8d79f7d" 

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "fixlog-storage"